Add support for Read, Update, and Delete for Messages
nylas/nylas-python pull request #305
Opened 2023-10-27 19:49 UTC by spang

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-10-27 19:52 UTC, spang commented
Unblocking my pet v3 side projects again! This could use a bit more testing—I've only verified that listing messages with `any_email` and `from` filters works so far. I'll continue to run it through its paces but I figured it's worth putting up a PR early so you know it exists. Figuring out how to properly deal with attributes that have the same names as Python keywords ("from", "in") was "fun"!

2023-10-27 19:58 UTC, spang commented on nylas/models/messages.py
> +"""
FYI, I have no idea if this docstring will end up in the autogenerated docs. Couldn't figure out any way to include a docstring on a functionally declared TypedDict.

2023-10-30 13:05 UTC, mrashed-dev requested changes
Thanks for this PR @spang 💪🏼 Left some PR comments!

2023-10-30 13:05 UTC, mrashed-dev commented on nylas/models/messages.py
> +    folder: NotRequired[List[str]]
I don't think there's any query/filter params for updating a message. For the `UpdateMessagRequest` the class hould also have `metadata` as a field that can be update and be a TypedDict:

```suggestion
class UpdateMessageRequest(TypedDict):

    """
    Request payload for updating a message.
    
    Attributes:
        starred: The message's starred status
        unread: The message's unread status
        folders: The message's folders
        metadata: A list of key-value pairs storing additional data
    """

    unread: NotRequired[bool]
    starred: NotRequired[bool]
    folder: NotRequired[List[str]]
    metadata: NotRequired[Dict[str, Any]]
```

2023-10-30 13:05 UTC, mrashed-dev commented on nylas/resources/messages.py
> +        query_params: UpdateMessageQueryParams,
Same as above, I don't think there's any query/filter params for updating a message

2023-10-31 00:00 UTC, spang commented
Alright @mrashed-dev, I think this is ready to merge! I've tested all the basic calls and a subset of query params manually from a script—IMO full/comprehensive testing should be done by a dedicated test rig for the SDK or SDKs and operate off of the API spec.

Also, just pointing out that this PR doesn't include send support—so no C, just R-U-D! Send can follow in a separate PR.

2023-10-31 14:13 UTC, mrashed-dev approved these changes
@spang thank you so much for the PR & changes! Message Send + Drafts + Threads + Schedule Send + Smart Compose is currently being worked on, so soon we will have full messages support on the Python SDK 😄

2023-10-31 14:13 UTC, merged