Update events.py to add capacity
nylas/nylas-python pull request #335
Opened 2024-01-25 03:31 UTC by atejada

Add capacity to the events response

https://nylas.atlassian.net/browse/TW-2502

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-01-25 08:26 UTC, mrashed-dev requested changes
Thanks @atejada ! Left a comment.

2024-01-25 08:26 UTC, mrashed-dev commented on nylas/models/events.py
> +    capacity: int
Capacity should be optional, can you mark it as so and move it down with the optional fields? Thanks!

2024-01-25 20:37 UTC, atejada commented
@mrashed-dev Should be done 😁

2024-01-29 11:45 UTC, mrashed-dev approved these changes
Thanks @atejada !

2024-01-29 11:46 UTC, merged